

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."comment_history_inserts"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$BEGIN
    IF EXISTS (
        SELECT 1
        FROM "public"."CLIENT"
        WHERE id = NEW.id_client AND history = TRUE
    ) THEN
        INSERT INTO "public"."COMMENT_HISTORY" ("id_client", "pseudo", "question", "response")
        VALUES (NEW.id_client, NEW.pseudo, NEW.question, NEW.response);
    END IF;
    RETURN NEW;
END;$$;


ALTER FUNCTION "public"."comment_history_inserts"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."execute_sql"("query" "text") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
    EXECUTE query;
END;
$$;


ALTER FUNCTION "public"."execute_sql"("query" "text") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."CLIENT" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "name" "text" NOT NULL,
    "header_question" "text",
    "header_condition" "text",
    "address" "text",
    "email" "text",
    "phone" "text",
    "history" boolean DEFAULT false
);


ALTER TABLE "public"."CLIENT" OWNER TO "postgres";


ALTER TABLE "public"."CLIENT" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."CLIENT_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."COMMENT" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_client" bigint NOT NULL,
    "pseudo" "text" NOT NULL,
    "question" "text" NOT NULL,
    "response" "text" NOT NULL,
    "isAdmin" boolean DEFAULT false,
    "isDeleted" boolean DEFAULT false
);


ALTER TABLE "public"."COMMENT" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."COMMENT_HISTORY" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_client" bigint NOT NULL,
    "pseudo" "text" NOT NULL,
    "question" "text" NOT NULL,
    "response" "text" NOT NULL
);


ALTER TABLE "public"."COMMENT_HISTORY" OWNER TO "postgres";


COMMENT ON TABLE "public"."COMMENT_HISTORY" IS 'This is a duplicate of COMMENT';



ALTER TABLE "public"."COMMENT_HISTORY" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."COMMENT_HISTORY_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."COMMENT" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."COMMENT_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."DATASOURCE" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "value" "text" NOT NULL,
    "type" smallint NOT NULL,
    "id_client" bigint NOT NULL
);


ALTER TABLE "public"."DATASOURCE" OWNER TO "postgres";


ALTER TABLE "public"."DATASOURCE" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."DATASOURCE_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."TRANSLATION" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "key" "text" NOT NULL,
    "en" "text",
    "es" "text",
    "fr" "text"
);


ALTER TABLE "public"."TRANSLATION" OWNER TO "postgres";


ALTER TABLE "public"."TRANSLATION" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."TRANSLATION_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."contact_csv" (
    "id" integer NOT NULL,
    "Contact name" "text",
    "Job title" "text",
    "Business phone" "text",
    "Account" "text",
    "Email" "text",
    "Mobile phone" "text",
    "Modified on" "text",
    "Data entry compliance" "text"
);


ALTER TABLE "public"."contact_csv" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."contact_csv_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."contact_csv_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."contact_csv_id_seq" OWNED BY "public"."contact_csv"."id";



ALTER TABLE ONLY "public"."contact_csv" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."contact_csv_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."CLIENT"
    ADD CONSTRAINT "CLIENT_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."COMMENT_HISTORY"
    ADD CONSTRAINT "COMMENT_HISTORY_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."COMMENT"
    ADD CONSTRAINT "COMMENT_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."DATASOURCE"
    ADD CONSTRAINT "DATASOURCE_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."TRANSLATION"
    ADD CONSTRAINT "TRANSLATION_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."contact_csv"
    ADD CONSTRAINT "contact_csv_pkey" PRIMARY KEY ("id");



CREATE OR REPLACE TRIGGER "trg_comment_history" AFTER INSERT ON "public"."COMMENT" FOR EACH ROW EXECUTE FUNCTION "public"."comment_history_inserts"();

ALTER TABLE "public"."COMMENT" DISABLE TRIGGER "trg_comment_history";



ALTER TABLE ONLY "public"."COMMENT_HISTORY"
    ADD CONSTRAINT "COMMENT_HISTORY_id_client_fkey" FOREIGN KEY ("id_client") REFERENCES "public"."CLIENT"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."COMMENT_HISTORY"
    ADD CONSTRAINT "COMMENT_HISTORY_id_client_fkey1" FOREIGN KEY ("id_client") REFERENCES "public"."CLIENT"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."COMMENT"
    ADD CONSTRAINT "COMMENT_id_client_fkey" FOREIGN KEY ("id_client") REFERENCES "public"."CLIENT"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."COMMENT"
    ADD CONSTRAINT "COMMENT_id_client_fkey1" FOREIGN KEY ("id_client") REFERENCES "public"."CLIENT"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."DATASOURCE"
    ADD CONSTRAINT "DATASOURCE_id_client_fkey" FOREIGN KEY ("id_client") REFERENCES "public"."CLIENT"("id");



CREATE POLICY "Allow anonymous access" ON "public"."COMMENT" FOR SELECT TO "anon" USING (true);



ALTER TABLE "public"."COMMENT" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."COMMENT_HISTORY" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."TRANSLATION" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."COMMENT";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."comment_history_inserts"() TO "anon";
GRANT ALL ON FUNCTION "public"."comment_history_inserts"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."comment_history_inserts"() TO "service_role";



GRANT ALL ON FUNCTION "public"."execute_sql"("query" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."execute_sql"("query" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."execute_sql"("query" "text") TO "service_role";


















GRANT ALL ON TABLE "public"."CLIENT" TO "anon";
GRANT ALL ON TABLE "public"."CLIENT" TO "authenticated";
GRANT ALL ON TABLE "public"."CLIENT" TO "service_role";



GRANT ALL ON SEQUENCE "public"."CLIENT_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."CLIENT_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."CLIENT_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."COMMENT" TO "anon";
GRANT ALL ON TABLE "public"."COMMENT" TO "authenticated";
GRANT ALL ON TABLE "public"."COMMENT" TO "service_role";



GRANT ALL ON TABLE "public"."COMMENT_HISTORY" TO "anon";
GRANT ALL ON TABLE "public"."COMMENT_HISTORY" TO "authenticated";
GRANT ALL ON TABLE "public"."COMMENT_HISTORY" TO "service_role";



GRANT ALL ON SEQUENCE "public"."COMMENT_HISTORY_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."COMMENT_HISTORY_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."COMMENT_HISTORY_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."COMMENT_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."COMMENT_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."COMMENT_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."DATASOURCE" TO "anon";
GRANT ALL ON TABLE "public"."DATASOURCE" TO "authenticated";
GRANT ALL ON TABLE "public"."DATASOURCE" TO "service_role";



GRANT ALL ON SEQUENCE "public"."DATASOURCE_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."DATASOURCE_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."DATASOURCE_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."TRANSLATION" TO "anon";
GRANT ALL ON TABLE "public"."TRANSLATION" TO "authenticated";
GRANT ALL ON TABLE "public"."TRANSLATION" TO "service_role";



GRANT ALL ON SEQUENCE "public"."TRANSLATION_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."TRANSLATION_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."TRANSLATION_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."contact_csv" TO "anon";
GRANT ALL ON TABLE "public"."contact_csv" TO "authenticated";
GRANT ALL ON TABLE "public"."contact_csv" TO "service_role";



GRANT ALL ON SEQUENCE "public"."contact_csv_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."contact_csv_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."contact_csv_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
