

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."CLIENT" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "name" "text" NOT NULL,
    "header_question" "text",
    "header_condition" "text",
    "condition" "text",
    "address" "text",
    "email" "text",
    "phone" "text"
);


ALTER TABLE "public"."CLIENT" OWNER TO "postgres";


ALTER TABLE "public"."CLIENT" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."CLIENT_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."COMMENT" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_client" bigint NOT NULL,
    "pseudo" "text" NOT NULL,
    "question" "text" NOT NULL,
    "response" "text" NOT NULL,
    "isAdmin" boolean DEFAULT false
);


ALTER TABLE "public"."COMMENT" OWNER TO "postgres";


ALTER TABLE "public"."COMMENT" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."COMMENT_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."CLIENT"
    ADD CONSTRAINT "CLIENT_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."COMMENT"
    ADD CONSTRAINT "COMMENT_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."COMMENT"
    ADD CONSTRAINT "COMMENT_id_client_fkey" FOREIGN KEY ("id_client") REFERENCES "public"."CLIENT"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."COMMENT"
    ADD CONSTRAINT "COMMENT_id_client_fkey1" FOREIGN KEY ("id_client") REFERENCES "public"."CLIENT"("id") ON DELETE CASCADE;



CREATE POLICY "Allow anonymous access" ON "public"."COMMENT" FOR SELECT TO "anon" USING (true);



ALTER TABLE "public"."CLIENT" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."COMMENT" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."COMMENT";



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



































































































































































































GRANT ALL ON TABLE "public"."CLIENT" TO "anon";
GRANT ALL ON TABLE "public"."CLIENT" TO "authenticated";
GRANT ALL ON TABLE "public"."CLIENT" TO "service_role";



GRANT ALL ON SEQUENCE "public"."CLIENT_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."CLIENT_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."CLIENT_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."COMMENT" TO "anon";
GRANT ALL ON TABLE "public"."COMMENT" TO "authenticated";
GRANT ALL ON TABLE "public"."COMMENT" TO "service_role";



GRANT ALL ON SEQUENCE "public"."COMMENT_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."COMMENT_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."COMMENT_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
