CREATE TABLE IF NOT EXISTS "public"."SERVICE" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "en" text,
    "duration" smallint DEFAULT 30,
    "es" text,
    "fr" text,
    "cat" smallint
);

CREATE TABLE IF NOT EXISTS "public"."CLIENT" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "guid" "text" NOT NULL,
    "key" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."peluqueria_csv_en" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "task" "text" NOT NULL,
    "category" "text" NOT NULL,
	"price" "text" NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."INFORAI" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "text" "text" NOT NULL,
    "categ" integer NOT NULL,
	"lang" "text" NOT NULL,
);

CREATE TABLE IF NOT EXISTS "public"."AVAILABILITY" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "slot" "text",
    "id_client" integer NOT NULL,
    "cur_date" "date"
);

CREATE TABLE IF NOT EXISTS "public"."CITA" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_service" integer NOT NULL,
    "whatsapp" "text",
    "name" "text",
    "id_client" integer NOT NULL,
    "start_date" timestamp without time zone
);

CREATE TABLE IF NOT EXISTS "public"."COMMENT" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_client" integer NOT NULL,
    "pseudo" "text" NOT NULL,
    "question" "text" NOT NULL,
    "response" "text" NOT NULL,
    "viewed" boolean DEFAULT false,
    "isai" boolean DEFAULT false,
    "created" timestamp without time zone,
    "categ" integer DEFAULT 3
);

ALTER SEQUENCE public."COMMENT_id_seq" RESTART WITH 1;

DROP VIEW comment_union;
CREATE VIEW comment_union AS
SELECT 
    pseudo,
    question AS content,
    created,
	isai,
    0 AS type
FROM "public"."COMMENT" WHERE isai is true OR response = '-'
UNION ALL
SELECT 
    pseudo,
    response AS content,
    created,
	isai,
    1 AS type
FROM "public"."COMMENT" WHERE response != '-';

CREATE TABLE IF NOT EXISTS "public"."COMMENT_HISTORY" (
    "id" integer NOT NULL,
    "id_client" integer NOT NULL,
    "pseudo" "text" NOT NULL,
    "question" "text" NOT NULL,
    "response" "text" NOT NULL
);

DROP VIEW IF EXISTS construction_en;

CREATE VIEW construction_en AS
SELECT 
    task || 
    CASE 
        WHEN category = 'Service' THEN ' Service' 
        ELSE '' 
    END AS title,price
FROM "public"."construction_csv_en";

CREATE VIEW peluqueria_en AS
SELECT 
    task AS title, price 
FROM "public"."peluqueria_csv_en";

